"""empty message

Revision ID: 38371457eeb7
Revises: 38cc8bb456c4
Create Date: 2025-07-03 02:22:11.218115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38371457eeb7'
down_revision = '38cc8bb456c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'documents', ['document_id'], ['id'])

    with op.batch_alter_table('vector_embeddings', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'documents', ['document_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vector_embeddings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###